name: DNSValidator

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: {} # Manually trigger the workflow

jobs:
  dnsvalidator:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install & Run Dnsvalidator
        run: |
          git clone https://github.com/vortexau/dnsvalidator.git
          cd dnsvalidator
          python -m pip install -r requirements.txt
          python setup.py install
          cd ..
          rm -rf dnsvalidator
          dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 20 -o resolvers.txt
        
      - name: Commit & push output to repository
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add resolvers.txt
          git commit -m "Updated resolvers"
          git push "https://zy9ard3:${{ secrets.DNSVALIDATOR }}@github.com/zy9ard3/fresh-resolvers.git" HEAD:master --follow-tags
