name: DNSValidator

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: {} # Manually trigger the workflow

jobs:
  dnsvalidator:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
        
      - name: Install Dnsvalidator
        run: |
          git clone https://github.com/vortexau/dnsvalidator.git
          cd dnsvalidator
          python -m pip install -r requirements.txt
          python setup.py install
          cd ..
          rm -rf dnsvalidator
        
      - name: Run DNSValidator
        run: dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 20 -o resolvers.txt

      - name: Commit and push output to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "balakumarc92584@gmail.com"
          git add resolvers.txt
          git commit -m "Updated resolvers.txt"
          git push
